export enum PackageStateEnum {
    ANNOUNCED = "ANNOUNCED",
    IN_CENTRAL = "IN_CENTRAL",
    PICKED_UP = "PICKED_UP",
    REDIRECTED_TO_DHL = "REDIRECTED_TO_DHL",
    IN_CAR = "IN_CAR",
    DELIVERY_FAILED = "DELIVERY_FAILED",
    ADDRESS_NOT_FOUND = "ADDRESS_NOT_FOUND",
    DELIVERED = "DELIVERED",
    PICKUP_FAILED = "PICKUP_FAILED",
    REQUESTED_PICKUP = "REQUESTED_PICKUP",
    CANCELED = "CANCELED"
}
